import type { AnthropicChatModelToolCapabilitiesByName } from "@tanstack/ai-anthropic";
import type { OpenAIChatModel, OpenAIChatModelToolCapabilitiesByName } from "@tanstack/ai-openai";

/**
 * The installed OpenAI adapter omits some empty-tool models from its capability map type. Preserve
 * those exact empty tuples while requiring every runtime chat model to be represented.
 */
type OpenAIExactToolCapabilitiesByName = {
  readonly [Model in OpenAIChatModel]: Model extends keyof OpenAIChatModelToolCapabilitiesByName
    ? OpenAIChatModelToolCapabilitiesByName[Model]
    : readonly [];
};

/** Runtime counterpart of @tanstack/ai-openai 0.24.1's type-only model tool metadata. */
export const openAIModelToolCapabilities = {
  "gpt-5.2": [
    "web_search",
    "web_search_preview",
    "file_search",
    "image_generation",
    "code_interpreter",
    "mcp",
    "computer_use",
    "local_shell",
    "shell",
    "apply_patch",
  ],
  "gpt-5.2-pro": [
    "web_search",
    "web_search_preview",
    "file_search",
    "image_generation",
    "code_interpreter",
    "mcp",
    "computer_use",
    "local_shell",
    "shell",
    "apply_patch",
  ],
  "gpt-5.2-chat-latest": [
    "web_search",
    "web_search_preview",
    "file_search",
    "image_generation",
    "code_interpreter",
    "mcp",
  ],
  "gpt-5.1": [
    "web_search",
    "web_search_preview",
    "file_search",
    "image_generation",
    "code_interpreter",
    "mcp",
    "computer_use",
    "local_shell",
    "shell",
    "apply_patch",
  ],
  "gpt-5.1-codex": [
    "file_search",
    "code_interpreter",
    "mcp",
    "local_shell",
    "shell",
    "apply_patch",
  ],
  "gpt-5": [
    "web_search",
    "web_search_preview",
    "file_search",
    "image_generation",
    "code_interpreter",
    "mcp",
    "computer_use",
    "local_shell",
    "shell",
    "apply_patch",
  ],
  "gpt-5-mini": [
    "web_search",
    "web_search_preview",
    "file_search",
    "image_generation",
    "code_interpreter",
    "mcp",
    "computer_use",
    "local_shell",
    "shell",
    "apply_patch",
  ],
  "gpt-5-nano": [
    "web_search",
    "web_search_preview",
    "file_search",
    "image_generation",
    "code_interpreter",
    "mcp",
    "computer_use",
    "local_shell",
    "shell",
    "apply_patch",
  ],
  "gpt-5-pro": [
    "web_search",
    "web_search_preview",
    "file_search",
    "image_generation",
    "code_interpreter",
    "mcp",
    "computer_use",
    "local_shell",
    "shell",
    "apply_patch",
  ],
  "gpt-5-codex": ["file_search", "code_interpreter", "mcp", "local_shell", "shell", "apply_patch"],
  "o3-deep-research": [
    "web_search",
    "web_search_preview",
    "file_search",
    "image_generation",
    "code_interpreter",
    "mcp",
    "computer_use",
    "local_shell",
    "shell",
    "apply_patch",
  ],
  "o4-mini-deep-research": [
    "web_search",
    "web_search_preview",
    "file_search",
    "image_generation",
    "code_interpreter",
    "mcp",
    "computer_use",
    "local_shell",
    "shell",
    "apply_patch",
  ],
  "o3-pro": [
    "web_search",
    "web_search_preview",
    "file_search",
    "image_generation",
    "code_interpreter",
    "mcp",
    "computer_use",
    "local_shell",
    "shell",
    "apply_patch",
  ],
  "gpt-audio": [],
  "gpt-audio-mini": [],
  o3: [
    "web_search",
    "web_search_preview",
    "file_search",
    "image_generation",
    "code_interpreter",
    "mcp",
    "computer_use",
    "local_shell",
    "shell",
    "apply_patch",
  ],
  "o4-mini": [
    "web_search",
    "web_search_preview",
    "file_search",
    "image_generation",
    "code_interpreter",
    "mcp",
    "computer_use",
    "local_shell",
    "shell",
    "apply_patch",
  ],
  "gpt-4.1": [
    "web_search",
    "web_search_preview",
    "file_search",
    "image_generation",
    "code_interpreter",
    "mcp",
    "computer_use",
    "local_shell",
    "shell",
    "apply_patch",
  ],
  "gpt-4.1-mini": [
    "web_search",
    "web_search_preview",
    "file_search",
    "image_generation",
    "code_interpreter",
    "mcp",
    "computer_use",
    "local_shell",
    "shell",
    "apply_patch",
  ],
  "gpt-4.1-nano": [
    "web_search",
    "web_search_preview",
    "file_search",
    "image_generation",
    "code_interpreter",
    "mcp",
    "computer_use",
    "local_shell",
    "shell",
    "apply_patch",
  ],
  "o1-pro": ["file_search", "code_interpreter", "mcp"],
  "computer-use-preview": ["computer_use"],
  "gpt-4o-mini-search-preview": ["web_search_preview"],
  "gpt-4o-search-preview": ["web_search_preview"],
  "o3-mini": [
    "web_search",
    "web_search_preview",
    "file_search",
    "image_generation",
    "code_interpreter",
    "mcp",
    "computer_use",
    "local_shell",
    "shell",
    "apply_patch",
  ],
  "gpt-4o-mini-audio": [],
  o1: ["file_search", "code_interpreter", "mcp"],
  "gpt-4o": ["web_search", "file_search", "image_generation", "code_interpreter", "mcp"],
  "gpt-4o-audio": [],
  "gpt-4o-mini": ["web_search", "file_search", "image_generation", "code_interpreter", "mcp"],
  "gpt-4-turbo": [],
  "chatgpt-4o-latest": [
    "web_search",
    "web_search_preview",
    "file_search",
    "image_generation",
    "code_interpreter",
    "mcp",
  ],
  "gpt-5.1-codex-mini": [
    "file_search",
    "code_interpreter",
    "mcp",
    "local_shell",
    "shell",
    "apply_patch",
  ],
  "codex-mini-latest": [
    "file_search",
    "code_interpreter",
    "mcp",
    "local_shell",
    "shell",
    "apply_patch",
  ],
  "gpt-3.5-turbo": [],
  "gpt-4": [],
  "gpt-5.1-chat-latest": [
    "web_search",
    "web_search_preview",
    "file_search",
    "image_generation",
    "code_interpreter",
    "mcp",
  ],
  "gpt-5-chat-latest": [
    "web_search",
    "web_search_preview",
    "file_search",
    "image_generation",
    "code_interpreter",
    "mcp",
  ],
  "gpt-5.4-mini": [
    "web_search",
    "web_search_preview",
    "file_search",
    "image_generation",
    "code_interpreter",
    "mcp",
    "computer_use",
    "local_shell",
    "shell",
    "apply_patch",
  ],
  "gpt-5.4-nano": [
    "web_search",
    "web_search_preview",
    "file_search",
    "image_generation",
    "code_interpreter",
    "mcp",
    "computer_use",
    "local_shell",
    "shell",
    "apply_patch",
  ],
  "gpt-5.4-image-2": [
    "web_search",
    "web_search_preview",
    "file_search",
    "image_generation",
    "code_interpreter",
    "mcp",
    "computer_use",
    "local_shell",
    "shell",
    "apply_patch",
  ],
  "gpt-5.6": [
    "web_search",
    "web_search_preview",
    "file_search",
    "image_generation",
    "code_interpreter",
    "mcp",
    "computer_use",
    "local_shell",
    "shell",
    "apply_patch",
  ],
  "gpt-5.6-sol": [
    "web_search",
    "web_search_preview",
    "file_search",
    "image_generation",
    "code_interpreter",
    "mcp",
    "computer_use",
    "local_shell",
    "shell",
    "apply_patch",
  ],
  "gpt-5.6-terra": [
    "web_search",
    "web_search_preview",
    "file_search",
    "image_generation",
    "code_interpreter",
    "mcp",
    "computer_use",
    "local_shell",
    "shell",
    "apply_patch",
  ],
  "gpt-5.6-luna": [
    "web_search",
    "web_search_preview",
    "file_search",
    "image_generation",
    "code_interpreter",
    "mcp",
    "computer_use",
    "local_shell",
    "shell",
    "apply_patch",
  ],
  "gpt-5.5": [
    "web_search",
    "web_search_preview",
    "file_search",
    "image_generation",
    "code_interpreter",
    "mcp",
    "computer_use",
    "local_shell",
    "shell",
    "apply_patch",
  ],
  "gpt-5.5-pro": [
    "web_search",
    "web_search_preview",
    "file_search",
    "image_generation",
    "code_interpreter",
    "mcp",
    "computer_use",
    "local_shell",
    "shell",
    "apply_patch",
  ],
  "gpt-chat-latest": [
    "web_search",
    "web_search_preview",
    "file_search",
    "image_generation",
    "code_interpreter",
    "mcp",
    "computer_use",
    "local_shell",
    "shell",
    "apply_patch",
  ],
  "gpt-5.6-luna-pro": [],
  "gpt-5.6-sol-pro": [],
  "gpt-5.6-terra-pro": [],
  "gpt-6-astra": [],
  "gpt-6-astra-pro": [],
  "gpt-6-luna": [],
  "gpt-6-luna-pro": [],
  "gpt-6-sol": [],
  "gpt-6-sol-pro": [],
} as const satisfies OpenAIExactToolCapabilitiesByName;

/** Runtime counterpart of @tanstack/ai-anthropic 0.19.1's type-only model tool metadata. */
export const anthropicModelToolCapabilities = {
  "claude-opus-4-6": [
    "web_search",
    "web_fetch",
    "code_execution",
    "computer_use",
    "bash",
    "text_editor",
    "memory",
  ],
  "claude-opus-4-5": [
    "web_search",
    "web_fetch",
    "code_execution",
    "computer_use",
    "bash",
    "text_editor",
    "memory",
  ],
  "claude-sonnet-4-6": [
    "web_search",
    "web_fetch",
    "code_execution",
    "computer_use",
    "bash",
    "text_editor",
    "memory",
  ],
  "claude-sonnet-4-5": [
    "web_search",
    "web_fetch",
    "code_execution",
    "computer_use",
    "bash",
    "text_editor",
    "memory",
  ],
  "claude-haiku-4-5": [
    "web_search",
    "web_fetch",
    "code_execution",
    "computer_use",
    "bash",
    "text_editor",
    "memory",
  ],
  "claude-opus-4-1": [
    "web_search",
    "web_fetch",
    "code_execution",
    "computer_use",
    "bash",
    "text_editor",
    "memory",
  ],
  "claude-opus-4-7": [
    "web_search",
    "web_fetch",
    "code_execution",
    "computer_use",
    "bash",
    "text_editor",
    "memory",
  ],
  "claude-opus-4-8": [
    "web_search",
    "web_fetch",
    "code_execution",
    "computer_use",
    "bash",
    "text_editor",
    "memory",
  ],
  "claude-fable-5": [
    "web_search",
    "web_fetch",
    "code_execution",
    "computer_use",
    "bash",
    "text_editor",
    "memory",
  ],
  "claude-sonnet-5": [
    "web_search",
    "web_fetch",
    "code_execution",
    "computer_use",
    "bash",
    "text_editor",
    "memory",
  ],
  "claude-opus-5": [
    "web_search",
    "web_fetch",
    "code_execution",
    "computer_use",
    "bash",
    "text_editor",
    "memory",
  ],
  "claude-opus-5-fast": [],
  "claude-opus-5-5": ["web_search", "web_fetch", "code_execution", "bash", "text_editor", "memory"],
  "claude-fable-5-1": [
    "web_search",
    "web_fetch",
    "code_execution",
    "computer_use",
    "bash",
    "text_editor",
    "memory",
  ],
} as const satisfies AnthropicChatModelToolCapabilitiesByName;
