import { Effect, Either } from "effect";
import {
  DirectImageExecutionFailed,
  makeImageMediaWorkflow,
  type ImageFeatureApi,
  type ImageRouteDecision,
  type ImageRouterApi,
} from "memory-agent";
import { describe, expect, it } from "vite-plus/test";

const decision: ImageRouteDecision = {
  type: "selected",
  mode: "auto",
  preference: "balanced",
  initiatorChatRouteId: "chat:anthropic:claude-test",
  initiatorChatModel: "claude-test",
  executorMediaRouteId: "media:openai:direct_adapter:gpt-image-2",
  executorMediaModel: { type: "explicit", model: "gpt-image-2" },
  provider: "openai",
  initiatorProvider: "openai",
  crossProvider: false,
  crossProviderConsentMode: "always",
  crossProviderApprovalRequired: false,
  accountId: "account-1",
  executionMode: "direct_adapter",
  estimatedCostUsd: 0.1,
  score: 1,
  reasons: ["fixture"],
  ranking: [],
};
const feature: ImageFeatureApi = {
  status: Effect.succeed({ imageGenerationEnabled: true }),
  setImageGenerationEnabled: () => Effect.die("unused"),
};
const router: ImageRouterApi = {
  select: () => Effect.succeed(decision),
  rerouteAfterFailure: (failedDecision, reason) =>
    Effect.succeed({
      type: "confirmation_required",
      failedDecision,
      reason,
      alternatives: [],
    }),
};
const request = {
  initiatorChatRouteId: decision.initiatorChatRouteId,
  prompt: "a small blue bird",
  approved: true,
};

function attachmentStore(saved: Uint8Array[]) {
  return {
    save: (bytes: Uint8Array) => {
      saved.push(bytes);
      return Effect.succeed({
        id: "a".repeat(64),
        mimeType: "image/png" as const,
        bytes: bytes.byteLength,
        createdAt: "2026-09-20T00:00:00.000Z",
      });
    },
  };
}

describe("ImageMediaWorkflow", () => {
  it("requires explicit approval before paid execution", async () => {
    let executions = 0;
    const workflow = makeImageMediaWorkflow(
      feature,
      router,
      {
        generate: () => {
          executions += 1;
          return Effect.die("must not execute");
        },
      },
      attachmentStore([]),
    );
    const result = await Effect.runPromise(
      Effect.either(workflow.generate({ ...request, approved: false })),
    );
    expect(Either.isLeft(result) && result.left._tag).toBe("ImageMediaApprovalRequired");
    expect(executions).toBe(0);
  });

  it("persists generated bytes and returns provenance without embedding base64", async () => {
    const bytes = Uint8Array.from([137, 80, 78, 71, 13, 10, 26, 10]);
    const saved: Uint8Array[] = [];
    const workflow = makeImageMediaWorkflow(
      feature,
      router,
      {
        generate: () =>
          Effect.succeed({
            bytes,
            contentType: "image/png",
            providerRequestId: "request-1",
            usage: { outputTokens: 42 },
          }),
      },
      attachmentStore(saved),
    );
    const asset = await Effect.runPromise(workflow.generate(request));
    expect(saved).toEqual([bytes]);
    expect(asset).toMatchObject({
      initiatorChatModel: "claude-test",
      executorMediaRouteId: decision.executorMediaRouteId,
      executorMediaModel: { type: "explicit", model: "gpt-image-2" },
      executionMode: "direct_adapter",
      estimatedCostUsd: 0.1,
      providerRequestId: "request-1",
      usage: { outputTokens: 42 },
    });
    expect(JSON.stringify(asset)).not.toContain("base64");
  });

  it("binds one-time cross-provider approval and revalidates consent before execution", async () => {
    const crossDecision: ImageRouteDecision = {
      ...decision,
      initiatorProvider: "anthropic",
      crossProvider: true,
      crossProviderConsentMode: "ask",
      crossProviderApprovalRequired: true,
    };
    let mode: "disabled" | "ask" | "always" = "ask";
    let executions = 0;
    const workflow = makeImageMediaWorkflow(
      feature,
      { ...router, select: () => Effect.succeed(crossDecision) },
      {
        generate: () => {
          executions += 1;
          return Effect.succeed({ bytes: Uint8Array.of(1), contentType: "image/png" });
        },
      },
      attachmentStore([]),
      undefined,
      {
        read: Effect.succeed({ version: 1, pairs: {} }),
        decide: (pair) =>
          Effect.succeed({
            ...pair,
            crossProvider: true,
            mode,
            allowedWithoutPrompt: mode === "always",
            requiresApproval: mode === "ask",
            reasons: [],
            settingsVersion: 1,
          }),
        set: () => Effect.die("unused"),
      },
    );
    const first = await Effect.runPromise(Effect.either(workflow.generate(request)));
    expect(Either.isLeft(first) && first.left).toMatchObject({
      _tag: "ImageMediaApprovalRequired",
      reason: "cross_provider",
    });
    if (!Either.isLeft(first) || first.left._tag !== "ImageMediaApprovalRequired") return;
    const approval = first.left.approval!;
    await Effect.runPromise(
      workflow.generate({ ...request, runId: approval.runId, crossProviderApproval: approval }),
    );
    expect(executions).toBe(1);
    const wrong = await Effect.runPromise(
      Effect.either(
        workflow.generate({
          ...request,
          runId: approval.runId,
          crossProviderApproval: { ...approval, executorMediaRouteId: "tampered" },
        }),
      ),
    );
    expect(Either.isLeft(wrong) && wrong.left._tag).toBe("ImageMediaApprovalRequired");
    mode = "disabled";
    const revoked = await Effect.runPromise(
      Effect.either(
        workflow.generate({ ...request, runId: approval.runId, crossProviderApproval: approval }),
      ),
    );
    expect(Either.isLeft(revoked) && revoked.left).toMatchObject({
      _tag: "ImageMediaUnavailable",
      reason: "cross-provider consent disabled",
    });
    expect(executions).toBe(1);
  });

  it("returns confirmation-required reroute evidence after execution failure", async () => {
    const workflow = makeImageMediaWorkflow(
      feature,
      router,
      {
        generate: () =>
          Effect.fail(new DirectImageExecutionFailed({ reason: "provider_rejected" })),
      },
      attachmentStore([]),
    );
    const result = await Effect.runPromise(Effect.either(workflow.generate(request)));
    expect(Either.isLeft(result) && result.left).toMatchObject({
      _tag: "ImageMediaExecutionFailed",
      reroute: { type: "confirmation_required", alternatives: [] },
    });
  });
});
